# Configuration for API Gateway

endpoints: 
  pokeApi:
    paths: 
      - '/api/v2/pokemon'
      - '/api/v2/pokemon/*'
    methods: 
      - GET
  pokeApiProtected:
    paths: 
      - '/api/v2/ability'
    methods: 
      - GET

pipelines:
  pokemonService:
    endpoints:
      - pokeApi
    policies:
      proxy:
        forwardTo: 'https://pokeapi.co'
  starwarsService:
    endpoints:
      - pokeApiProtected
    policies:
      jwt: 
        verifySecret: true # Todo false case.
      proxy:
        forwardTo: 'https://pokeapi.co'

        
  
