# Configuration for API Gateway

endpoints: 
  pokeApi:
    paths: 
      - '/api/v2/pokemon'
      - '/api/v2/pokemon/*'
    methods: 
      - GET
  pokeApiProtectedJWT:
    paths: 
      - '/api/v2/ability'
    methods: 
      - GET
  pokeApiProtectedBasicAuth:
    paths: 
      - '/api/v2/type'
    methods: 
      - GET

pipelines:
  pokeApiService:
    endpoints:
      - pokeApi
    policies:
      proxy:
        forwardTo: 'https://pokeapi.co'
  pokeApiProtectedJWTService:
    endpoints:
      - pokeApiProtectedJWT
    policies:
      jwt: 
        verifySecret: true # //TODO: false case.
      proxy:
        forwardTo: 'https://pokeapi.co'
  pokeApiProtectedBasicAuthService:
    endpoints:
      - pokeApiProtectedBasicAuth
    policies:
      basicAuth: 
      proxy:
        forwardTo: 'https://pokeapi.co'

        
  
